const base=["Obst & Gemüse","Backwaren","Kühlung","Fleisch & Wurst","Vorrat","Getränke","Tiefkühlung","Drogerie","Sonstiges"];
const rules=[[/banane|apfel|äpfel|tomate|gurke|kartoffel|salat|zwiebel|paprika/,"Obst & Gemüse"],[/brot|brötchen|toast|baguette/,"Backwaren"],[/milch|butter|joghurt|käse|gouda|quark|sahne|eier?/,"Kühlung"],[/hack|fleisch|hähnchen|wurst|salami|schinken/,"Fleisch & Wurst"],[/nudel|reis|kaffee|mehl|zucker|müsli|öl|essig/,"Vorrat"],[/wasser|cola|saft|bier|limo/,"Getränke"],[/pizza|pommes|eis|tiefkühl/,"Tiefkühlung"],[/spül|waschmittel|toilettenpapier|küchenrolle|shampoo|seife/,"Drogerie"]];
const retailer={rewe1:"rewe",rewe2:"rewe",lidl1:"lidl",lidl2:"lidl",aldi1:"aldi-sued",aldi2:"aldi-sued",netto1:"netto-marken-discount",norma1:"norma"};
const $=s=>document.querySelector(s);
function cat(n){n=n.toLowerCase();for(const [r,c] of rules)if(r.test(n))return c;return"Sonstiges"}
function load(){try{let x=JSON.parse(localStorage.getItem("ew9"));if(x?.items&&x?.routes)return x}catch(e){}return{items:[],routes:{},store:"rewe1",offers:{}}}
let st=load(),edit=[],offerTimer=null;function save(){localStorage.setItem("ew9",JSON.stringify(st))}function route(){return st.routes[st.store]||base}
function esc(s){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
function show(id,title){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));$("#"+id).classList.add("active");$("#title").textContent=title;window.scrollTo(0,0)}
function offerFor(x){return st.offers?.[x.id]?.[0]||null}
function node(x,shop){let o=offerFor(x),d=document.createElement("div");d.className="item"+(x.checked?" checked":"")+(o?" has-offer":"");d.innerHTML=`<input class="check" data-id="${x.id}" type="checkbox" ${x.checked?"checked":""}><div><div class="name">${esc(x.name)}</div><div class="meta"><button class="tag ${x.mode}" data-mode="${x.id}">${x.mode==="recurring"?"dauerhaft":"einmalig"}</button><span class="tag">${x.cat}</span>${o?'<span class="tag offer-tag">ANGEBOT</span>':""}</div>${o?`<div class="offer-line"><strong>${esc(o.price||"")}</strong> · ${esc(o.title||"")} ${o.brand?`(${esc(o.brand)})`:""}<br>${esc(o.valid||"")}</div>`:""}</div>${shop?"":`<button class="delete" data-del="${x.id}">×</button>`}`;return d}
function bind(box){box.querySelectorAll(".check").forEach(b=>b.onchange=e=>{let x=st.items.find(i=>i.id===e.target.dataset.id);x.checked=e.target.checked;save();render()});box.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>{let x=st.items.find(i=>i.id===b.dataset.mode);x.mode=x.mode==="once"?"recurring":"once";save();render()});box.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>{st.items=st.items.filter(i=>i.id!==b.dataset.del);delete st.offers[b.dataset.del];save();render();scheduleOffers()})}
function sorted(){let o=route();return[...st.items].sort((a,b)=>(o.indexOf(a.cat)<0?99:o.indexOf(a.cat))-(o.indexOf(b.cat)<0?99:o.indexOf(b.cat)))}
function render(){let a=$("#items");a.innerHTML="";st.items.forEach(x=>a.append(node(x,false)));bind(a);let b=$("#shopItems");b.innerHTML="";sorted().forEach(x=>b.append(node(x,true)));bind(b);$("#storeSelect").value=st.store;$("#routePreview").innerHTML=route().map(x=>`<span>${x}</span>`).join("");$("#shopStore").textContent=$("#storeSelect").selectedOptions[0]?.textContent||"";let done=st.items.filter(x=>x.checked).length,total=st.items.length;$("#progressText").textContent=`${done} von ${total} erledigt`;$("#progressBar").style.width=total?done/total*100+"%":"0%";let hits=Object.values(st.offers||{}).filter(x=>x?.length).length;$("#storeOfferSummary").textContent=hits?`${hits} Artikel deiner Liste haben aktuell passende Angebote.`:"Aktuell keine passenden Angebote geladen."}
function add(){let v=$("#input").value.trim();if(!v)return;v.split(/,|;|\n/).map(x=>x.trim()).filter(Boolean).forEach(n=>st.items.push({id:crypto.randomUUID(),name:n[0].toUpperCase()+n.slice(1),cat:cat(n),mode:"once",checked:false}));$("#input").value="";save();render();scheduleOffers()}
function scheduleOffers(){clearTimeout(offerTimer);offerTimer=setTimeout(loadOffers,250)}
async function loadOffers(){if(!st.items.length)return;$("#syncState").textContent="Aktuelle Angebote werden automatisch geprüft …";$("#storeOfferSummary").textContent="Angebote werden automatisch geprüft …";try{const res=await fetch("/api/match-offers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({retailer:retailer[st.store],items:st.items.map(x=>({id:x.id,name:x.name}))})});if(!res.ok)throw new Error();const data=await res.json();st.offers=data.matches||{};save();$("#syncState").textContent=`Angebote aktualisiert · ${new Date().toLocaleTimeString("de-DE",{hour:"2-digit",minute:"2-digit"})}`;render()}catch(e){$("#syncState").textContent="Angebote konnten gerade nicht aktualisiert werden. Liste funktioniert weiter offline.";$("#storeOfferSummary").textContent="Keine Verbindung zum Angebotsdienst.";}}
$("#add").onclick=add;$("#input").onkeydown=e=>{if(e.key==="Enter"){e.preventDefault();add()}};$("#toStore").onclick=()=>{show("store","Filiale wählen");scheduleOffers()};$("#storeSelect").onchange=()=>{st.store=$("#storeSelect").value;st.offers={};save();render();scheduleOffers()};$("#start").onclick=()=>{if(!st.items.length){alert("Füge zuerst mindestens einen Artikel hinzu.");return}show("shop","Einkauf");scheduleOffers()};$("#finish").onclick=()=>{st.items=st.items.filter(x=>!(x.mode==="once"&&x.checked));st.items.forEach(x=>{if(x.mode==="recurring")x.checked=false});st.offers={};save();render();show("list","Einkaufsliste");scheduleOffers()};$("#settings").onclick=()=>show("settingsScreen","Einstellungen");document.querySelectorAll(".back").forEach(b=>b.onclick=()=>show(b.dataset.to,b.dataset.to==="list"?"Einkaufsliste":"Filiale wählen"));
$("#editRoute").onclick=()=>{edit=[...route()];routeEditor();show("route","Laufweg anpassen")};function routeEditor(){$("#routeEditor").innerHTML=edit.map((c,i)=>`<div class="route-row"><b>${c}</b><button data-u="${i}">↑</button><button data-d="${i}">↓</button></div>`).join("");$("#routeEditor").querySelectorAll("[data-u]").forEach(b=>b.onclick=()=>mv(+b.dataset.u,-1));$("#routeEditor").querySelectorAll("[data-d]").forEach(b=>b.onclick=()=>mv(+b.dataset.d,1))}function mv(i,d){let j=i+d;if(j<0||j>=edit.length)return;[edit[i],edit[j]]=[edit[j],edit[i]];routeEditor()}$("#saveRoute").onclick=()=>{st.routes[st.store]=[...edit];save();render();show("store","Filiale wählen")};
$("#export").onclick=()=>{let blob=new Blob([JSON.stringify({version:9,data:st},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="einkaufsweg-backup.json";a.click();URL.revokeObjectURL(a.href)};$("#importFile").onchange=async e=>{try{let b=JSON.parse(await e.target.files[0].text());if(!b.data?.items)throw 0;st=b.data;save();render();scheduleOffers();alert("Backup wiederhergestellt.")}catch(_){alert("Backup konnte nicht gelesen werden.")}e.target.value=""};render();scheduleOffers();